### ISSUE TITLE
OCRA don't delete extracted file from temp directory and pollute the user's Temp

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ocra#11]
<img width="633" alt="Screen Shot 2021-10-04 at 6 01 40 PM" src="https://user-images.githubusercontent.com/2169738/135884804-9591ed9b-837b-497e-9744-11294788627f.png">

single `ocra????.tmp` is about 350Mb and it creates on each run so after 10 runs user will have `-~3.5Gb` which is not good

We didn't use `--debug-extract` which may prevent delete, so this logic to be investigated in OCRA code https://github.com/larsch/ocra

cc @ronaldtse

**Comment by ronaldtse** [comment]
@maxirmx once we can use tebako, we don't need to care about this, right?

**Comment by maxirmx** [comment]
I believe I can fix some Ocra issues, including this one,  and make Ocra look better for AV software.
If we can have code sign certificate and sign both package and packaged executables it can be long term solution.

I am not so sure about tebako for WIndows. It may take 1-2 months and hit another wall.  
So, if Windows version of metanorma single file executable is important, I would try to fix Ocra first.

**Comment by ronaldtse** [comment]
@maxirmx I have encountered this issue before on Windows, perhaps a year ago, where the temp directory became huge. I do not think Ocra has any expansion caching capability, i.e. it just extracts the full package every time. If any caching is to be done, there needs to be a quick way of determining integrity of the pre-expanded file tree via file hashing.

**Comment by maxirmx** [comment]
Fixed by
https://github.com/metanorma/isodoc/commit/32ab5c8c8ea2dead791b59069b377169c059d5ea
